app:
  botToken: ${BOT_TOKEN}
  polyglot_book: ${POLYGLOT_BOOK}
  syzygy_directory: ${SYZYGY_DIRECTORY}
  workerId: ${WORKER_ID:sosa-worker}

spring:
  application:
    name: sosa-worker

  main:
    web-application-type: none

  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    virtual-host: /
    # Recommended for publishers:
    publisher-confirm-type: correlated
    publisher-returns: true
