apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosa-master
  labels:
    app: sosa-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sosa-master
  template:
    metadata:
      name: sosa-master
      labels:
        app: sosa-master
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: sosa-master
          image: coriamauricio/sosa-master:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              sleep:
                seconds: 60
          env:
            - name: RABBIT_HOST
              value: "chesstango-rabbit-svc.default.svc.cluster.local"
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: bot_token
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_password
          envFrom:
            - configMapRef:
                name: sosa-master-config
