apiVersion: batch/v1
kind: Job
metadata:
  name: sosa-worker
spec:
  completions: 15000
  parallelism: 2
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: sosa-worker
    spec:
      restartPolicy: Never
      volumes:
        - name: ipc-volume
          emptyDir: { }
        - name: books-volume
          persistentVolumeClaim:
            claimName: chesstango-book-pvc
      initContainers:
        - name: sosa-worker-init
          image: coriamauricio/sosa-worker-init:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKER_INIT_DIRECTORY
              value: "/init-ipc-dir"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBIT_HOST
              value: "chesstango-rabbit-svc.default.svc.cluster.local"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_password
          volumeMounts:
            - name: ipc-volume
              mountPath: /init-ipc-dir
      containers:
        - name: sosa-worker
          image: coriamauricio/sosa-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKER_INIT_DIRECTORY
              value: "/init-ipc-dir"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBIT_HOST
              value: "chesstango-rabbit-svc.default.svc.cluster.local"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: rabbit_password
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sosa-secrets
                  key: bot_token
          envFrom:
            - configMapRef:
                name: sosa-worker-config
          volumeMounts:
            - name: ipc-volume
              mountPath: /init-ipc-dir
            - name: books-volume
              mountPath: /books/