app:
  botToken: ${BOT_TOKEN}
  challengeJob: ${CHALLENGE_JOB:false}
  challengeTypes: ${CHALLENGE_TYPES:bullet,blitz,rapid}
  challengeExpire: 15
  gameWatchDog: ${GAME_WATCHDOG:false}
  gameExpire: 30


spring:
  application:
    name: sosa-master

  main:
    web-application-type: none

  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    virtual-host: /
    # Recommended for publishers:
    publisher-confirm-type: correlated
    publisher-returns: true

    listener:
      simple:
        # Sets the number of messages the broker will deliver to a consumer before receiving an acknowledgment.
        # Setting this to 1 ensures only one unacknowledged message is held by the consumer at any time.
        prefetch: 1
        # Sets the number of consumers created for the listener. Set to 1 for a single consumer instance.
        concurrency: 1
        # Sets the maximum number of consumers. Set to 1 to prevent dynamic scaling beyond a single consumer.
        max-concurrency: 1

  quartz:
    job-store-type: memory
    properties.org.quartz.threadPool.threadCount: 1
